export interface Droit {
  id: bigint;
  listRepertoire: boolean;
  listStock: boolean;
  listLivraison: boolean;
  listFacture: boolean;
  listAchatLivraison: boolean;
  listAchatFacture: boolean;
  listAchatLivraisonEtranger: boolean;
  ajouterRepertoire: boolean;
  ajouterStock: boolean;
  ajouterLivraison: boolean;
  ajouterFacture: boolean;
  ajouterAchatLivraison: boolean;
  ajouterAchatFacture: boolean;
  ajouterAchatLivraisonEtranger: boolean;
  modifRepertoire: boolean;
  modifStock: boolean;
  modifLivraison: boolean;
  modifFacture: boolean;
  modifAchatLivraison: boolean;
  modifAchatFacture: boolean;
  modifAchatLivraisonEtranger: boolean;
  suppRepertoire: boolean;
  suppStock: boolean;
  suppLivraison: boolean;
  suppFacture: boolean;
  suppAchatLivraison: boolean;
  suppAchatFacture: boolean;
  suppAchatLivraisonEtranger: boolean;
  etatRepertoire: boolean;
  etatStock: boolean;
  etatLivraison: boolean;
  etatFacture: boolean;
  etatAchatLivraison: boolean;
  etatAchatFacture: boolean;
  etatAchatLivraisonEtranger: boolean;
  imprimeRepertoire: boolean;
  imprimeStock: boolean;
  imprimeLivraison: boolean;
  imprimeFacture: boolean;
  imprimerAchatLivraison: boolean;
  imprimerAchatFacture: boolean;
  imprimerAchatLivraisonEtranger: boolean;
}

export function initObjectDroit(): Droit {
  return {
    id: BigInt(0),
    listRepertoire: false,
    listStock: false,
    listLivraison: false,
    listFacture: false,
    listAchatLivraison: false,
    listAchatFacture: false,
    listAchatLivraisonEtranger: false,
    ajouterRepertoire: false,
    ajouterStock: false,
    ajouterLivraison: false,
    ajouterFacture: false,
    ajouterAchatLivraison: false,
    ajouterAchatFacture: false,
    ajouterAchatLivraisonEtranger: false,
    modifRepertoire: false,
    modifStock: false,
    modifLivraison: false,
    modifFacture: false,
    modifAchatLivraison: false,
    modifAchatFacture: false,
    modifAchatLivraisonEtranger: false,
    suppRepertoire: false,
    suppStock: false,
    suppLivraison: false,
    suppFacture: false,
    suppAchatLivraison: false,
    suppAchatFacture: false,
    suppAchatLivraisonEtranger: false,
    etatRepertoire: false,
    etatStock: false,
    etatLivraison: false,
    etatFacture: false,
    etatAchatLivraison: false,
    etatAchatFacture: false,
    etatAchatLivraisonEtranger: false,
    imprimeRepertoire: false,
    imprimeStock: false,
    imprimeLivraison: false,
    imprimeFacture: false,
    imprimerAchatLivraison: false,
    imprimerAchatFacture: false,
    imprimerAchatLivraisonEtranger: false,
  };
}