export enum Permission {
    ALL = 'ALL',
    CONSULTER_STOCK = 'CONSULTER_STOCK',
    AJOUTER_STOCK = 'AJOUTER_STOCK',
    MODIFIER_STOCK = 'MODIFIER_STOCK',
    SUPPRIMER_STOCK = 'SUPPRIMER_STOCK',
    CONSULTER_REPERTOIRE = 'CONSULTER_REPERTOIRE',
    AJOUTER_REPERTOIRE = 'AJOUTER_REPERTOIRE',
    MODIFIER_REPERTOIRE = 'MODIFIER_REPERTOIRE',
    SUPPRIMER_REPERTOIRE = 'SUPPRIMER_REPERTOIRE'
}
