import { environment } from "src/environments/environment";

const BASE_URL = environment.production ? 'https://kabir-backend-nest-js.vercel.app/api' : 'http://localhost:8080/api';
const FACTURE = `facture`;
const BON_SORTIE = `bon-sortie`;

export const ENDPOINTS = {
  VILLE: {
    getAll: `${BASE_URL}/ville`,
    getById: (id: bigint) => `${BASE_URL}/ville/${id}`,
    create: `${BASE_URL}/ville`,
    update: (id: bigint) => `${BASE_URL}/ville/${id}`,
    delete: (id: bigint) => `${BASE_URL}/ville/${id}`,
    exist: `${BASE_URL}/ville/exist`,
  },
  PAYS: {
    getAll: `${BASE_URL}/pays`,
    getById: (id: bigint) => `${BASE_URL}/pays/${id}`,
    create: `${BASE_URL}/pays`,
    update: (id: bigint) => `${BASE_URL}/pays/${id}`,
    delete: (id: bigint) => `${BASE_URL}/pays/${id}`,
    search: `${BASE_URL}/pays/search`,
    exist: `${BASE_URL}/pays/exist`
  },
  ETABLISSEMENT: {
    getAll: `${BASE_URL}/etablissement`,
    getById: (id: bigint) => `${BASE_URL}/etablissement/${id}`,
    create: `${BASE_URL}/etablissement`,
    update: (id: bigint) => `${BASE_URL}/etablissement/${id}`,
    delete: (id: bigint) => `${BASE_URL}/etablissement/${id}`,
  },
  STOCK_DEPOT: {
    getAll: `${BASE_URL}/stock-depot`,
    getById: (id: bigint) => `${BASE_URL}/stock-depot/${id}`,
    getByIdRequest: (id: bigint) => `${BASE_URL}/stock-depot/response/${id}`,
    create: `${BASE_URL}/stock-depot`,
    update: (id: bigint) => `${BASE_URL}/stock-depot/${id}`,
    delete: (id: bigint) => `${BASE_URL}/stock-depot/${id}`,
  },
  REPERTOIRE: {
    getAll: `${BASE_URL}/repertoire`,
    getById: (id: bigint) => `${BASE_URL}/repertoire/${id}`,
    create: `${BASE_URL}/repertoire`,
    update: (id: bigint) => `${BASE_URL}/repertoire/${id}`,
    delete: (id: bigint) => `${BASE_URL}/repertoire/${id}`,
    exist: `${BASE_URL}/repertoire/exist`,
    search: `${BASE_URL}/repertoire/search`,
    searchPersonnel: `${BASE_URL}/repertoire/search-personnel`,
    updateNbrOperation: (id: bigint, nbrOperation: number) => `${BASE_URL}/repertoire/${id}/update-nbr-operation/${nbrOperation}`,
  },
  ABSENCE: {
    getAll: `${BASE_URL}/absence`,
    getById: (id: bigint) => `${BASE_URL}/absence/${id}`,
    create: `${BASE_URL}/absence`,
    update: (id: bigint) => `${BASE_URL}/absence/${id}`,
    delete: (id: bigint) => `${BASE_URL}/absence/${id}`,
    exist: `${BASE_URL}/absence/exist`,
    search: `${BASE_URL}/absence/search`,
  },
  FOURNISSEUR: {
    getAll: `${BASE_URL}/fournisseur`,
    getById: (id: bigint) => `${BASE_URL}/fournisseur/${id}`,
    create: `${BASE_URL}/fournisseur`,
    update: (id: bigint) => `${BASE_URL}/fournisseur/${id}`,
    delete: (id: bigint) => `${BASE_URL}/fournisseur/${id}`,
    exist: `${BASE_URL}/fournisseur/exist`,
    search: `${BASE_URL}/fournisseur/search`,
    updateNbrOperation: (id: bigint, nbrOperation: number) => `${BASE_URL}/fournisseur/${id}/update-nbr-operation/${nbrOperation}`,
  },
  COMPTE: {
    getAll: `${BASE_URL}/compte`,
    getById: (id: bigint) => `${BASE_URL}/compte/${id}`,
    create: `${BASE_URL}/compte`,
    update: (id: bigint) => `${BASE_URL}/compte/${id}`,
    delete: (id: bigint) => `${BASE_URL}/compte/${id}`,
    search: `${BASE_URL}/compte/search`,
  },
  PERSONNEL: {
    getAll: `${BASE_URL}/personnel`,
    getAllAlowed: `${BASE_URL}/personnel/allowed`,
    getById: (id: bigint) => `${BASE_URL}/personnel/${id}`,
    create: `${BASE_URL}/personnel`,
    update: (id: bigint) => `${BASE_URL}/personnel/${id}`,
    delete: (id: bigint) => `${BASE_URL}/personnel/${id}`,
    exist: `${BASE_URL}/personnel/exist`,
    search: `${BASE_URL}/personnel/search`,
    present: `${BASE_URL}/personnel/present`
  },
  PRIME: {
    getAll: `${BASE_URL}/prime`,
    getById: (id: bigint) => `${BASE_URL}/prime/${id}`,
    create: `${BASE_URL}/prime`,
    update: (id: bigint) => `${BASE_URL}/prime/${id}`,
    delete: (id: bigint) => `${BASE_URL}/prime/${id}`,
    search: `${BASE_URL}/prime/search`,
  },
  STOCK: {
    getAll: `${BASE_URL}/stock`,
    getById: (id: bigint) => `${BASE_URL}/stock/${id}`,
    create: `${BASE_URL}/stock`,
    update: (id: bigint) => `${BASE_URL}/stock/${id}`,
    delete: (id: bigint) => `${BASE_URL}/stock/${id}`,
    exist: `${BASE_URL}/stock/exist`,
    search: `${BASE_URL}/stock/search`,
    updateQteStock: (id: bigint) => `${BASE_URL}/stock/${id}/update-qte-stock`,
    updateQteStockImport: (id: bigint) => `${BASE_URL}/stock/${id}/update-qte-stock-import`,
    updateQteStockFacturer: (id: bigint) => `${BASE_URL}/stock/${id}/update-qte-stock-facturer`,
  },
  VOITURE: {
    getAll: `${BASE_URL}/voiture`,
    getById: (id: bigint) => `${BASE_URL}/voiture/${id}`,
    create: `${BASE_URL}/voiture`,
    update: (id: bigint) => `${BASE_URL}/voiture/${id}`,
    delete: (id: bigint) => `${BASE_URL}/voiture/${id}`,
    exist: `${BASE_URL}/voiture/exist`,
    search: `${BASE_URL}/voiture/search`,
  },
  LIVRAISON: {
    getAll: `${BASE_URL}/livraison`,
    getById: (id: bigint) => `${BASE_URL}/livraison/${id}`,
    getByIdWithDetLivraison: (id: bigint) => `${BASE_URL}/livraison/${id}/with-det-livraison`,
    create: `${BASE_URL}/livraison`,
    update: (id: bigint) => `${BASE_URL}/livraison/${id}`,
    delete: (id: bigint) => `${BASE_URL}/livraison/${id}`,
    exist: `${BASE_URL}/livraison/exist`,
    search: `${BASE_URL}/livraison/search`,
    present: `${BASE_URL}/livraison/present`,
    getLastNumLivraison: `${BASE_URL}/livraison/last-num-livraison`
  },
  DET_LIVRAISON: {
    getAll: `${BASE_URL}/det-livraison`,
    getById: (id: bigint) => `${BASE_URL}/det-livraison/${id}`,
    create: `${BASE_URL}/det-livraison`,
    update: (id: bigint) => `${BASE_URL}/det-livraison/${id}`,
    delete: (id: bigint) => `${BASE_URL}/det-livraison/${id}`,
    getByLivraison: (idLivraison: bigint) => `${BASE_URL}/det-livraison/livraison/${idLivraison}`,
    exist: `${BASE_URL}/det-livraison/exist`,
    search: `${BASE_URL}/det-livraison/search`,
    present: `${BASE_URL}/det-livraison/present`
  },
  FACTURE: {
    getAll: `${BASE_URL}/${FACTURE}`,
    getById: (id: bigint) => `${BASE_URL}/${FACTURE}/${id}`,
    getByIdRequest: (id: bigint) => `${BASE_URL}/${FACTURE}/response/${id}`,
    create: `${BASE_URL}/${FACTURE}`,
    update: (id: bigint) => `${BASE_URL}/${FACTURE}/${id}`,
    delete: (id: bigint) => `${BASE_URL}/${FACTURE}/${id}`,
  },
  BON_SORTIE: {
    getAll: `${BASE_URL}/${BON_SORTIE}`,
    getById: (id: bigint) => `${BASE_URL}/${BON_SORTIE}/${id}`,
    getByIdRequest: (id: bigint) => `${BASE_URL}/${BON_SORTIE}/response/${id}`,
    create: `${BASE_URL}/${BON_SORTIE}`,
    update: (id: bigint) => `${BASE_URL}/${BON_SORTIE}/${id}`,
    delete: (id: bigint) => `${BASE_URL}/${BON_SORTIE}/${id}`,
  },
  ACHAT_SIMPLE: {
    getAll: `${BASE_URL}/achat-simple`,
    getById: (id: bigint) => `${BASE_URL}/achat-simple/${id}`,
    getByIdRequest: (id: bigint) => `${BASE_URL}/achat-simple/response/${id}`,
    create: `${BASE_URL}/achat-simple`,
    update: (id: bigint) => `${BASE_URL}/achat-simple/${id}`,
    delete: (id: bigint) => `${BASE_URL}/achat-simple/${id}`,
    exist: `${BASE_URL}/achat-simple/exist`,
    search: `${BASE_URL}/achat-simple/search`,
    present: `${BASE_URL}/achat-simple/present`
  }
};
